// Generated by rstantools.  Do not edit by hand.

/*
    ffc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ffc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ffc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_ardf_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 133> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 36, column 2 to column 44)",
  " (in 'string', line 38, column 2 to column 23)",
  " (in 'string', line 40, column 2 to column 14)",
  " (in 'string', line 42, column 2 to column 25)",
  " (in 'string', line 44, column 2 to column 38)",
  " (in 'string', line 46, column 2 to column 19)",
  " (in 'string', line 50, column 2 to column 28)",
  " (in 'string', line 51, column 2 to column 64)",
  " (in 'string', line 64, column 2 to column 47)",
  " (in 'string', line 117, column 2 to column 42)",
  " (in 'string', line 122, column 2 to column 32)",
  " (in 'string', line 123, column 2 to column 36)",
  " (in 'string', line 54, column 4 to column 14)",
  " (in 'string', line 55, column 4 to column 14)",
  " (in 'string', line 58, column 8 to column 26)",
  " (in 'string', line 59, column 8 to column 32)",
  " (in 'string', line 57, column 30 to line 60, column 7)",
  " (in 'string', line 57, column 6 to line 60, column 7)",
  " (in 'string', line 56, column 24 to line 61, column 5)",
  " (in 'string', line 56, column 4 to line 61, column 5)",
  " (in 'string', line 53, column 2 to line 62, column 3)",
  " (in 'string', line 65, column 2 to column 38)",
  " (in 'string', line 69, column 8 to column 57)",
  " (in 'string', line 68, column 28 to line 70, column 7)",
  " (in 'string', line 68, column 6 to line 70, column 7)",
  " (in 'string', line 67, column 21 to line 71, column 5)",
  " (in 'string', line 67, column 4 to line 71, column 5)",
  " (in 'string', line 66, column 22 to line 72, column 3)",
  " (in 'string', line 66, column 2 to line 72, column 3)",
  " (in 'string', line 76, column 6 to column 71)",
  " (in 'string', line 75, column 28 to line 77, column 5)",
  " (in 'string', line 75, column 4 to line 77, column 5)",
  " (in 'string', line 74, column 19 to line 78, column 3)",
  " (in 'string', line 74, column 2 to line 78, column 3)",
  " (in 'string', line 119, column 4 to column 66)",
  " (in 'string', line 118, column 25 to line 120, column 3)",
  " (in 'string', line 118, column 2 to line 120, column 3)",
  " (in 'string', line 126, column 6 to column 64)",
  " (in 'string', line 127, column 6 to column 77)",
  " (in 'string', line 125, column 28 to line 128, column 5)",
  " (in 'string', line 125, column 4 to line 128, column 5)",
  " (in 'string', line 124, column 18 to line 129, column 3)",
  " (in 'string', line 124, column 2 to line 129, column 3)",
  " (in 'string', line 131, column 11 to column 12)",
  " (in 'string', line 131, column 4 to column 41)",
  " (in 'string', line 133, column 6 to column 64)",
  " (in 'string', line 134, column 6 to line 135, column 63)",
  " (in 'string', line 132, column 28 to line 136, column 5)",
  " (in 'string', line 132, column 4 to line 136, column 5)",
  " (in 'string', line 130, column 18 to line 137, column 3)",
  " (in 'string', line 130, column 2 to line 137, column 3)",
  " (in 'string', line 82, column 2 to column 64)",
  " (in 'string', line 84, column 2 to column 21)",
  " (in 'string', line 89, column 32 to column 87)",
  " (in 'string', line 89, column 7 to column 87)",
  " (in 'string', line 88, column 32 to column 101)",
  " (in 'string', line 88, column 7 to line 89, column 87)",
  " (in 'string', line 87, column 32 to column 96)",
  " (in 'string', line 87, column 7 to line 89, column 87)",
  " (in 'string', line 86, column 27 to column 93)",
  " (in 'string', line 86, column 2 to line 89, column 87)",
  " (in 'string', line 94, column 33 to column 92)",
  " (in 'string', line 94, column 11 to column 92)",
  " (in 'string', line 93, column 28 to column 64)",
  " (in 'string', line 93, column 6 to line 94, column 92)",
  " (in 'string', line 92, column 21 to line 95, column 5)",
  " (in 'string', line 92, column 4 to line 95, column 5)",
  " (in 'string', line 91, column 22 to line 96, column 3)",
  " (in 'string', line 91, column 2 to line 96, column 3)",
  " (in 'string', line 98, column 2 to column 19)",
  " (in 'string', line 100, column 2 to column 33)",
  " (in 'string', line 103, column 11 to column 23)",
  " (in 'string', line 103, column 4 to column 74)",
  " (in 'string', line 105, column 13 to column 25)",
  " (in 'string', line 105, column 6 to column 42)",
  " (in 'string', line 106, column 6 to column 67)",
  " (in 'string', line 107, column 6 to column 70)",
  " (in 'string', line 104, column 20 to line 108, column 5)",
  " (in 'string', line 104, column 4 to line 108, column 5)",
  " (in 'string', line 110, column 13 to column 25)",
  " (in 'string', line 110, column 6 to column 67)",
  " (in 'string', line 111, column 6 to column 59)",
  " (in 'string', line 109, column 20 to line 112, column 5)",
  " (in 'string', line 109, column 4 to line 112, column 5)",
  " (in 'string', line 101, column 2 to line 113, column 3)",
  " (in 'string', line 17, column 2 to column 17)",
  " (in 'string', line 18, column 2 to column 20)",
  " (in 'string', line 19, column 2 to column 24)",
  " (in 'string', line 20, column 9 to column 17)",
  " (in 'string', line 20, column 2 to column 30)",
  " (in 'string', line 21, column 2 to column 17)",
  " (in 'string', line 22, column 2 to column 28)",
  " (in 'string', line 23, column 9 to column 21)",
  " (in 'string', line 23, column 2 to column 31)",
  " (in 'string', line 24, column 8 to column 20)",
  " (in 'string', line 24, column 2 to column 43)",
  " (in 'string', line 25, column 2 to column 22)",
  " (in 'string', line 26, column 2 to column 24)",
  " (in 'string', line 27, column 2 to column 24)",
  " (in 'string', line 28, column 2 to column 21)",
  " (in 'string', line 29, column 2 to column 17)",
  " (in 'string', line 30, column 2 to column 17)",
  " (in 'string', line 36, column 8 to column 9)",
  " (in 'string', line 36, column 11 to column 15)",
  " (in 'string', line 38, column 9 to column 10)",
  " (in 'string', line 38, column 12 to column 16)",
  " (in 'string', line 40, column 9 to column 10)",
  " (in 'string', line 42, column 9 to column 17)",
  " (in 'string', line 44, column 18 to column 26)",
  " (in 'string', line 50, column 9 to column 10)",
  " (in 'string', line 50, column 12 to column 20)",
  " (in 'string', line 51, column 9 to column 17)",
  " (in 'string', line 51, column 19 to column 23)",
  " (in 'string', line 64, column 9 to column 10)",
  " (in 'string', line 64, column 12 to column 16)",
  " (in 'string', line 117, column 18 to column 26)",
  " (in 'string', line 122, column 8 to column 9)",
  " (in 'string', line 122, column 11 to column 19)",
  " (in 'string', line 123, column 9 to column 10)",
  " (in 'string', line 123, column 12 to column 20)",
  " (in 'string', line 4, column 4 to column 20)",
  " (in 'string', line 5, column 11 to column 16)",
  " (in 'string', line 5, column 4 to column 20)",
  " (in 'string', line 6, column 4 to column 16)",
  " (in 'string', line 9, column 8 to column 22)",
  " (in 'string', line 10, column 8 to column 17)",
  " (in 'string', line 8, column 23 to line 11, column 7)",
  " (in 'string', line 8, column 6 to line 11, column 7)",
  " (in 'string', line 7, column 21 to line 12, column 5)",
  " (in 'string', line 7, column 4 to line 12, column 5)",
  " (in 'string', line 13, column 4 to column 13)",
  " (in 'string', line 3, column 35 to line 14, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
rep_each(const T0__& x_arg__, const int& K, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
rep_each(const T0__& x_arg__, const int& K, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& x = stan::math::to_ref(x_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int N = std::numeric_limits<int>::min();
    current_statement__ = 121;
    N = stan::math::rows(x);
    current_statement__ = 122;
    stan::math::validate_non_negative_index("y", "N * K", (N * K));
    Eigen::Matrix<local_scalar_t__,-1,1> y =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant((N * K), DUMMY_VAR__);
    int pos = std::numeric_limits<int>::min();
    current_statement__ = 124;
    pos = 1;
    current_statement__ = 130;
    for (int n = 1; n <= N; ++n) {
      current_statement__ = 128;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 125;
        stan::model::assign(y,
          stan::model::rvalue(x, "x", stan::model::index_uni(n)),
          "assigning variable y", stan::model::index_uni(pos));
        current_statement__ = 126;
        pos = (pos + 1);
      }
    }
    current_statement__ = 131;
    return y;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_ardf final : public model_base_crtp<model_ardf> {
private:
  int n;
  int n_lv;
  int n_series;
  Eigen::Matrix<double,-1,1> sample_var_data__;
  int M;
  int n_nonmissing;
  Eigen::Matrix<double,-1,1> flat_ys_data__;
  std::vector<int> obs_ind;
  int family;
  Eigen::Matrix<double,-1,1> prior_alpha_data__;
  Eigen::Matrix<double,-1,1> prior_sigma_data__;
  Eigen::Matrix<double,-1,1> prior_ar_data__;
  int P;
  Eigen::Matrix<double,-1,1> beta_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> sample_var{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> flat_ys{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_alpha{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_sigma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_ar{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> beta{nullptr, 0};
public:
  ~model_ardf() {}
  model_ardf(stan::io::var_context& context__, unsigned int
             random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_ardf_namespace::model_ardf";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 86;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 86;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "n_lv", "int",
        std::vector<size_t>{});
      n_lv = std::numeric_limits<int>::min();
      current_statement__ = 87;
      n_lv = context__.vals_i("n_lv")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "n_lv", n_lv, 0);
      current_statement__ = 88;
      context__.validate_dims("data initialization", "n_series", "int",
        std::vector<size_t>{});
      n_series = std::numeric_limits<int>::min();
      current_statement__ = 88;
      n_series = context__.vals_i("n_series")[(1 - 1)];
      current_statement__ = 88;
      stan::math::check_greater_or_equal(function__, "n_series", n_series, 0);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("sample_var", "n_series",
        n_series);
      current_statement__ = 90;
      context__.validate_dims("data initialization", "sample_var", "double",
        std::vector<size_t>{static_cast<size_t>(n_series)});
      sample_var_data__ = Eigen::Matrix<double,-1,1>::Constant(n_series,
                            std::numeric_limits<double>::quiet_NaN());
      new (&sample_var)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(sample_var_data__.data(),
        n_series);
      {
        std::vector<local_scalar_t__> sample_var_flat__;
        current_statement__ = 90;
        sample_var_flat__ = context__.vals_r("sample_var");
        current_statement__ = 90;
        pos__ = 1;
        current_statement__ = 90;
        for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
          current_statement__ = 90;
          stan::model::assign(sample_var, sample_var_flat__[(pos__ - 1)],
            "assigning variable sample_var", stan::model::index_uni(sym1__));
          current_statement__ = 90;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 91;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 91;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 92;
      context__.validate_dims("data initialization", "n_nonmissing", "int",
        std::vector<size_t>{});
      n_nonmissing = std::numeric_limits<int>::min();
      current_statement__ = 92;
      n_nonmissing = context__.vals_i("n_nonmissing")[(1 - 1)];
      current_statement__ = 92;
      stan::math::check_greater_or_equal(function__, "n_nonmissing",
        n_nonmissing, 0);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("flat_ys", "n_nonmissing",
        n_nonmissing);
      current_statement__ = 94;
      context__.validate_dims("data initialization", "flat_ys", "double",
        std::vector<size_t>{static_cast<size_t>(n_nonmissing)});
      flat_ys_data__ = Eigen::Matrix<double,-1,1>::Constant(n_nonmissing,
                         std::numeric_limits<double>::quiet_NaN());
      new (&flat_ys)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(flat_ys_data__.data(),
        n_nonmissing);
      {
        std::vector<local_scalar_t__> flat_ys_flat__;
        current_statement__ = 94;
        flat_ys_flat__ = context__.vals_r("flat_ys");
        current_statement__ = 94;
        pos__ = 1;
        current_statement__ = 94;
        for (int sym1__ = 1; sym1__ <= n_nonmissing; ++sym1__) {
          current_statement__ = 94;
          stan::model::assign(flat_ys, flat_ys_flat__[(pos__ - 1)],
            "assigning variable flat_ys", stan::model::index_uni(sym1__));
          current_statement__ = 94;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 95;
      stan::math::validate_non_negative_index("obs_ind", "n_nonmissing",
        n_nonmissing);
      current_statement__ = 96;
      context__.validate_dims("data initialization", "obs_ind", "int",
        std::vector<size_t>{static_cast<size_t>(n_nonmissing)});
      obs_ind = std::vector<int>(n_nonmissing,
                  std::numeric_limits<int>::min());
      current_statement__ = 96;
      obs_ind = context__.vals_i("obs_ind");
      current_statement__ = 96;
      stan::math::check_greater_or_equal(function__, "obs_ind", obs_ind, 0);
      current_statement__ = 97;
      context__.validate_dims("data initialization", "family", "int",
        std::vector<size_t>{});
      family = std::numeric_limits<int>::min();
      current_statement__ = 97;
      family = context__.vals_i("family")[(1 - 1)];
      current_statement__ = 97;
      stan::math::check_greater_or_equal(function__, "family", family, 1);
      current_statement__ = 98;
      context__.validate_dims("data initialization", "prior_alpha", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      prior_alpha_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                             std::numeric_limits<double>::quiet_NaN());
      new (&prior_alpha)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_alpha_data__.data(), 2);
      {
        std::vector<local_scalar_t__> prior_alpha_flat__;
        current_statement__ = 98;
        prior_alpha_flat__ = context__.vals_r("prior_alpha");
        current_statement__ = 98;
        pos__ = 1;
        current_statement__ = 98;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 98;
          stan::model::assign(prior_alpha, prior_alpha_flat__[(pos__ - 1)],
            "assigning variable prior_alpha", stan::model::index_uni(sym1__));
          current_statement__ = 98;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 99;
      context__.validate_dims("data initialization", "prior_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(3)});
      prior_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                             std::numeric_limits<double>::quiet_NaN());
      new (&prior_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_sigma_data__.data(), 3);
      {
        std::vector<local_scalar_t__> prior_sigma_flat__;
        current_statement__ = 99;
        prior_sigma_flat__ = context__.vals_r("prior_sigma");
        current_statement__ = 99;
        pos__ = 1;
        current_statement__ = 99;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 99;
          stan::model::assign(prior_sigma, prior_sigma_flat__[(pos__ - 1)],
            "assigning variable prior_sigma", stan::model::index_uni(sym1__));
          current_statement__ = 99;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 100;
      context__.validate_dims("data initialization", "prior_ar", "double",
        std::vector<size_t>{static_cast<size_t>(3)});
      prior_ar_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                          std::numeric_limits<double>::quiet_NaN());
      new (&prior_ar)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_ar_data__.data(), 3);
      {
        std::vector<local_scalar_t__> prior_ar_flat__;
        current_statement__ = 100;
        prior_ar_flat__ = context__.vals_r("prior_ar");
        current_statement__ = 100;
        pos__ = 1;
        current_statement__ = 100;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 100;
          stan::model::assign(prior_ar, prior_ar_flat__[(pos__ - 1)],
            "assigning variable prior_ar", stan::model::index_uni(sym1__));
          current_statement__ = 100;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 101;
      context__.validate_dims("data initialization", "P", "int",
        std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      current_statement__ = 101;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 101;
      stan::math::check_greater_or_equal(function__, "P", P, 1);
      current_statement__ = 102;
      context__.validate_dims("data initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(1)});
      beta_data__ = Eigen::Matrix<double,-1,1>::Constant(1,
                      std::numeric_limits<double>::quiet_NaN());
      new (&beta) Eigen::Map<Eigen::Matrix<double,-1,1>>(beta_data__.data(),
        1);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 102;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 102;
        pos__ = 1;
        current_statement__ = 102;
        for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
          current_statement__ = 102;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 102;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 103;
      stan::math::validate_non_negative_index("ar", "P", P);
      current_statement__ = 104;
      stan::math::validate_non_negative_index("ar", "n_lv", n_lv);
      current_statement__ = 105;
      stan::math::validate_non_negative_index("LV_z", "n", n);
      current_statement__ = 106;
      stan::math::validate_non_negative_index("LV_z", "n_lv", n_lv);
      current_statement__ = 107;
      stan::math::validate_non_negative_index("L", "M", M);
      current_statement__ = 108;
      stan::math::validate_non_negative_index("alpha", "n_series", n_series);
      current_statement__ = 109;
      stan::math::validate_non_negative_index("sigma_obs", "n_series",
        n_series);
      current_statement__ = 110;
      stan::math::validate_non_negative_index("trend", "n", n);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("trend", "n_series", n_series);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("Lambda", "n_series", n_series);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("Lambda", "n_lv", n_lv);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("LV", "n", n);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("LV", "n_lv", n_lv);
      current_statement__ = 116;
      stan::math::validate_non_negative_index("sigma_obs_adj", "n_series",
        n_series);
      current_statement__ = 117;
      stan::math::validate_non_negative_index("ypred", "n", n);
      current_statement__ = 118;
      stan::math::validate_non_negative_index("ypred", "n_series", n_series);
      current_statement__ = 119;
      stan::math::validate_non_negative_index("sigma_obs_vec", "n", n);
      current_statement__ = 120;
      stan::math::validate_non_negative_index("sigma_obs_vec", "n_series",
        n_series);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (P * n_lv) + (n * n_lv) + M + n_series + n_series + 1;
  }
  inline std::string model_name() const final {
    return "model_ardf";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_ardf_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<local_scalar_t__>> ar =
        std::vector<std::vector<local_scalar_t__>>(P,
          std::vector<local_scalar_t__>(n_lv, DUMMY_VAR__));
      current_statement__ = 1;
      ar = in__.template read_constrain_lub<
             std::vector<std::vector<local_scalar_t__>>, jacobian__>(-1, 1,
             lp__, P, n_lv);
      Eigen::Matrix<local_scalar_t__,-1,-1> LV_z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, n_lv, DUMMY_VAR__);
      current_statement__ = 2;
      LV_z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n,
               n_lv);
      Eigen::Matrix<local_scalar_t__,-1,1> L =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 3;
      L = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      current_statement__ = 4;
      alpha = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(n_series);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_obs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      current_statement__ = 5;
      sigma_obs = in__.template read_constrain_lb<
                    Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0,
                    lp__, n_series);
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 6;
      nu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> trend =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, n_series,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> Lambda =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_series, n_lv,
          DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(Lambda, stan::math::rep_matrix(0, n_series, n_lv),
        "assigning variable Lambda");
      {
        int index = std::numeric_limits<int>::min();
        current_statement__ = 14;
        index = 0;
        current_statement__ = 20;
        for (int j = 1; j <= n_lv; ++j) {
          current_statement__ = 18;
          for (int s = j; s <= n_series; ++s) {
            current_statement__ = 15;
            index = (index + 1);
            current_statement__ = 16;
            stan::model::assign(Lambda,
              stan::model::rvalue(L, "L", stan::model::index_uni(index)),
              "assigning variable Lambda", stan::model::index_uni(s),
              stan::model::index_uni(j));
          }
        }
      }
      Eigen::Matrix<local_scalar_t__,-1,-1> LV =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, n_lv, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(LV, stan::math::rep_matrix(0, n, n_lv),
        "assigning variable LV");
      current_statement__ = 22;
      stan::model::assign(LV,
        stan::model::rvalue(LV_z, "LV_z", stan::model::index_uni(1),
          stan::model::index_min_max(1, n_lv)), "assigning variable LV",
        stan::model::index_uni(1), stan::model::index_min_max(1, n_lv));
      current_statement__ = 29;
      for (int j = 1; j <= n_lv; ++j) {
        current_statement__ = 27;
        for (int p = 1; p <= P; ++p) {
          current_statement__ = 25;
          for (int t = (P + 1); t <= n; ++t) {
            current_statement__ = 23;
            stan::model::assign(LV,
              (stan::model::rvalue(LV, "LV", stan::model::index_uni(t),
                 stan::model::index_uni(j)) +
              ((stan::model::rvalue(ar, "ar", stan::model::index_uni(p),
                  stan::model::index_uni(j)) *
              stan::model::rvalue(LV, "LV", stan::model::index_uni((t - p)),
                stan::model::index_uni(j))) +
              stan::model::rvalue(LV_z, "LV_z", stan::model::index_uni(t),
                stan::model::index_uni(j)))), "assigning variable LV",
              stan::model::index_uni(t), stan::model::index_uni(j));
          }
        }
      }
      current_statement__ = 34;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 32;
        for (int s = 1; s <= n_series; ++s) {
          current_statement__ = 30;
          stan::model::assign(trend,
            (stan::model::rvalue(alpha, "alpha", stan::model::index_uni(s)) +
            stan::math::dot_product(
              stan::model::rvalue(Lambda, "Lambda",
                stan::model::index_uni(s), stan::model::index_omni()),
              stan::model::rvalue(LV, "LV", stan::model::index_uni(i),
                stan::model::index_omni()))), "assigning variable trend",
            stan::model::index_uni(i), stan::model::index_uni(s));
        }
      }
      {
        current_statement__ = 52;
        lp_accum__.add(stan::math::normal_lpdf<false>(alpha,
                         stan::model::rvalue(prior_alpha, "prior_alpha",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(prior_alpha, "prior_alpha",
                           stan::model::index_uni(2))));
        current_statement__ = 53;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(nu, 2, 0.1));
        current_statement__ = 61;
        if (stan::math::logical_eq(
              stan::model::rvalue(prior_sigma, "prior_sigma",
                stan::model::index_uni(3)), 1)) {
          current_statement__ = 60;
          lp_accum__.add(stan::math::normal_lpdf<false>(sigma_obs,
                           stan::model::rvalue(prior_sigma, "prior_sigma",
                             stan::model::index_uni(1)),
                           stan::model::rvalue(prior_sigma, "prior_sigma",
                             stan::model::index_uni(2))));
        } else {
          current_statement__ = 59;
          if (stan::math::logical_eq(
                stan::model::rvalue(prior_sigma, "prior_sigma",
                  stan::model::index_uni(3)), 2)) {
            current_statement__ = 58;
            lp_accum__.add(stan::math::beta_lpdf<false>(sigma_obs,
                             stan::model::rvalue(prior_sigma, "prior_sigma",
                               stan::model::index_uni(1)),
                             stan::model::rvalue(prior_sigma, "prior_sigma",
                               stan::model::index_uni(2))));
          } else {
            current_statement__ = 57;
            if (stan::math::logical_eq(
                  stan::model::rvalue(prior_sigma, "prior_sigma",
                    stan::model::index_uni(3)), 3)) {
              current_statement__ = 56;
              lp_accum__.add(stan::math::inv_gamma_lpdf<false>(sigma_obs,
                               stan::model::rvalue(prior_sigma,
                                 "prior_sigma", stan::model::index_uni(1)),
                               stan::model::rvalue(prior_sigma,
                                 "prior_sigma", stan::model::index_uni(2))));
            } else {
              current_statement__ = 55;
              if (stan::math::logical_eq(
                    stan::model::rvalue(prior_sigma, "prior_sigma",
                      stan::model::index_uni(3)), 4)) {
                current_statement__ = 54;
                lp_accum__.add(stan::math::exponential_lpdf<false>(sigma_obs,
                                 stan::model::rvalue(prior_sigma,
                                   "prior_sigma", stan::model::index_uni(1))));
              }
            }
          }
        }
        current_statement__ = 69;
        for (int j = 1; j <= n_lv; ++j) {
          current_statement__ = 67;
          for (int p = 1; p <= P; ++p) {
            current_statement__ = 65;
            if (stan::math::logical_eq(
                  stan::model::rvalue(prior_ar, "prior_ar",
                    stan::model::index_uni(3)), 1)) {
              current_statement__ = 64;
              lp_accum__.add(stan::math::std_normal_lpdf<false>(
                               stan::model::rvalue(ar, "ar",
                                 stan::model::index_uni(p),
                                 stan::model::index_uni(j))));
            } else {
              current_statement__ = 63;
              if (stan::math::logical_eq(
                    stan::model::rvalue(prior_ar, "prior_ar",
                      stan::model::index_uni(3)), 2)) {
                current_statement__ = 62;
                lp_accum__.add(stan::math::normal_lpdf<false>(
                                 stan::model::rvalue(ar, "ar",
                                   stan::model::index_uni(p),
                                   stan::model::index_uni(j)),
                                 stan::model::rvalue(prior_ar, "prior_ar",
                                   stan::model::index_uni(1)),
                                 stan::model::rvalue(prior_ar, "prior_ar",
                                   stan::model::index_uni(2))));
              }
            }
          }
        }
        current_statement__ = 70;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(L));
        current_statement__ = 71;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(LV_z)));
        {
          current_statement__ = 72;
          stan::math::validate_non_negative_index("flat_sigma_obs",
            "n_nonmissing", n_nonmissing);
          Eigen::Matrix<local_scalar_t__,-1,1> flat_sigma_obs =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_nonmissing,
              DUMMY_VAR__);
          current_statement__ = 73;
          stan::model::assign(flat_sigma_obs,
            stan::model::rvalue(rep_each(sigma_obs, n, pstream__),
              "rep_each(sigma_obs,\nn)", stan::model::index_multi(obs_ind)),
            "assigning variable flat_sigma_obs");
          current_statement__ = 79;
          if (stan::math::logical_eq(family, 1)) {
            current_statement__ = 74;
            stan::math::validate_non_negative_index("flat_trends",
              "n_nonmissing", n_nonmissing);
            Eigen::Matrix<local_scalar_t__,-1,-1> flat_trends =
              Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n_nonmissing,
                1, DUMMY_VAR__);
            current_statement__ = 76;
            stan::model::assign(flat_trends,
              stan::model::rvalue(stan::math::to_vector(trend),
                "to_vector(trend)", stan::model::index_multi(obs_ind)),
              "assigning variable flat_trends",
              stan::model::index_min_max(1, n_nonmissing),
              stan::model::index_uni(1));
            current_statement__ = 77;
            lp_accum__.add(stan::math::normal_id_glm_lpdf<propto__>(flat_ys,
                             flat_trends, 0.0, beta, flat_sigma_obs));
          }
          current_statement__ = 84;
          if (stan::math::logical_eq(family, 2)) {
            current_statement__ = 80;
            stan::math::validate_non_negative_index("flat_trends",
              "n_nonmissing", n_nonmissing);
            Eigen::Matrix<local_scalar_t__,-1,1> flat_trends =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_nonmissing,
                DUMMY_VAR__);
            current_statement__ = 81;
            stan::model::assign(flat_trends,
              stan::model::rvalue(stan::math::to_vector(trend),
                "to_vector(trend)", stan::model::index_multi(obs_ind)),
              "assigning variable flat_trends");
            current_statement__ = 82;
            lp_accum__.add(stan::math::student_t_lpdf<propto__>(flat_ys, nu,
                             flat_trends, flat_sigma_obs));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_ardf_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<double>> ar =
        std::vector<std::vector<double>>(P,
          std::vector<double>(n_lv, std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      ar = in__.template read_constrain_lub<
             std::vector<std::vector<local_scalar_t__>>, jacobian__>(-1, 1,
             lp__, P, n_lv);
      Eigen::Matrix<double,-1,-1> LV_z =
        Eigen::Matrix<double,-1,-1>::Constant(n, n_lv,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      LV_z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n,
               n_lv);
      Eigen::Matrix<double,-1,1> L =
        Eigen::Matrix<double,-1,1>::Constant(M,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      L = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(M);
      Eigen::Matrix<double,-1,1> alpha =
        Eigen::Matrix<double,-1,1>::Constant(n_series,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      alpha = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(n_series);
      Eigen::Matrix<double,-1,1> sigma_obs =
        Eigen::Matrix<double,-1,1>::Constant(n_series,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      sigma_obs = in__.template read_constrain_lb<
                    Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0,
                    lp__, n_series);
      double nu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      nu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      Eigen::Matrix<double,-1,-1> trend =
        Eigen::Matrix<double,-1,-1>::Constant(n, n_series,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> Lambda =
        Eigen::Matrix<double,-1,-1>::Constant(n_series, n_lv,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> LV =
        Eigen::Matrix<double,-1,-1>::Constant(n, n_lv,
          std::numeric_limits<double>::quiet_NaN());
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
          out__.write(ar[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(LV_z);
      out__.write(L);
      out__.write(alpha);
      out__.write(sigma_obs);
      out__.write(nu);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 8;
      stan::model::assign(Lambda, stan::math::rep_matrix(0, n_series, n_lv),
        "assigning variable Lambda");
      {
        int index = std::numeric_limits<int>::min();
        current_statement__ = 14;
        index = 0;
        current_statement__ = 20;
        for (int j = 1; j <= n_lv; ++j) {
          current_statement__ = 18;
          for (int s = j; s <= n_series; ++s) {
            current_statement__ = 15;
            index = (index + 1);
            current_statement__ = 16;
            stan::model::assign(Lambda,
              stan::model::rvalue(L, "L", stan::model::index_uni(index)),
              "assigning variable Lambda", stan::model::index_uni(s),
              stan::model::index_uni(j));
          }
        }
      }
      current_statement__ = 9;
      stan::model::assign(LV, stan::math::rep_matrix(0, n, n_lv),
        "assigning variable LV");
      current_statement__ = 22;
      stan::model::assign(LV,
        stan::model::rvalue(LV_z, "LV_z", stan::model::index_uni(1),
          stan::model::index_min_max(1, n_lv)), "assigning variable LV",
        stan::model::index_uni(1), stan::model::index_min_max(1, n_lv));
      current_statement__ = 29;
      for (int j = 1; j <= n_lv; ++j) {
        current_statement__ = 27;
        for (int p = 1; p <= P; ++p) {
          current_statement__ = 25;
          for (int t = (P + 1); t <= n; ++t) {
            current_statement__ = 23;
            stan::model::assign(LV,
              (stan::model::rvalue(LV, "LV", stan::model::index_uni(t),
                 stan::model::index_uni(j)) +
              ((stan::model::rvalue(ar, "ar", stan::model::index_uni(p),
                  stan::model::index_uni(j)) *
              stan::model::rvalue(LV, "LV", stan::model::index_uni((t - p)),
                stan::model::index_uni(j))) +
              stan::model::rvalue(LV_z, "LV_z", stan::model::index_uni(t),
                stan::model::index_uni(j)))), "assigning variable LV",
              stan::model::index_uni(t), stan::model::index_uni(j));
          }
        }
      }
      current_statement__ = 34;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 32;
        for (int s = 1; s <= n_series; ++s) {
          current_statement__ = 30;
          stan::model::assign(trend,
            (stan::model::rvalue(alpha, "alpha", stan::model::index_uni(s)) +
            stan::math::dot_product(
              stan::model::rvalue(Lambda, "Lambda",
                stan::model::index_uni(s), stan::model::index_omni()),
              stan::model::rvalue(LV, "LV", stan::model::index_uni(i),
                stan::model::index_omni()))), "assigning variable trend",
            stan::model::index_uni(i), stan::model::index_uni(s));
        }
      }
      if (emit_transformed_parameters__) {
        out__.write(trend);
        out__.write(Lambda);
        out__.write(LV);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> sigma_obs_adj =
        Eigen::Matrix<double,-1,1>::Constant(n_series,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 37;
      for (int s = 1; s <= n_series; ++s) {
        current_statement__ = 35;
        stan::model::assign(sigma_obs_adj,
          stan::math::sqrt(
            (stan::math::square(
               stan::model::rvalue(sigma_obs, "sigma_obs",
                 stan::model::index_uni(s))) +
            stan::model::rvalue(sample_var, "sample_var",
              stan::model::index_uni(s)))),
          "assigning variable sigma_obs_adj", stan::model::index_uni(s));
      }
      std::vector<std::vector<double>> ypred =
        std::vector<std::vector<double>>(n,
          std::vector<double>(n_series,
            std::numeric_limits<double>::quiet_NaN()));
      Eigen::Matrix<double,-1,-1> sigma_obs_vec =
        Eigen::Matrix<double,-1,-1>::Constant(n, n_series,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 43;
      if (stan::math::logical_eq(family, 1)) {
        current_statement__ = 41;
        for (int s = 1; s <= n_series; ++s) {
          current_statement__ = 38;
          stan::model::assign(sigma_obs_vec,
            stan::math::rep_vector(
              stan::model::rvalue(sigma_obs_adj, "sigma_obs_adj",
                stan::model::index_uni(s)), n),
            "assigning variable sigma_obs_vec",
            stan::model::index_min_max(1, n), stan::model::index_uni(s));
          current_statement__ = 39;
          stan::model::assign(ypred,
            stan::math::normal_rng(
              stan::model::rvalue(trend, "trend",
                stan::model::index_min_max(1, n), stan::model::index_uni(s)),
              stan::model::rvalue(sigma_obs_vec, "sigma_obs_vec",
                stan::model::index_min_max(1, n), stan::model::index_uni(s)),
              base_rng__), "assigning variable ypred",
            stan::model::index_min_max(1, n), stan::model::index_uni(s));
        }
      }
      current_statement__ = 51;
      if (stan::math::logical_eq(family, 2)) {
        current_statement__ = 44;
        stan::math::validate_non_negative_index("nu_vec", "n", n);
        Eigen::Matrix<double,-1,1> nu_vec =
          Eigen::Matrix<double,-1,1>::Constant(n,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 45;
        stan::model::assign(nu_vec, stan::math::rep_vector(nu, n),
          "assigning variable nu_vec");
        current_statement__ = 49;
        for (int s = 1; s <= n_series; ++s) {
          current_statement__ = 46;
          stan::model::assign(sigma_obs_vec,
            stan::math::rep_vector(
              stan::model::rvalue(sigma_obs_adj, "sigma_obs_adj",
                stan::model::index_uni(s)), n),
            "assigning variable sigma_obs_vec",
            stan::model::index_min_max(1, n), stan::model::index_uni(s));
          current_statement__ = 47;
          stan::model::assign(ypred,
            stan::math::student_t_rng(nu_vec,
              stan::model::rvalue(trend, "trend",
                stan::model::index_min_max(1, n), stan::model::index_uni(s)),
              stan::model::rvalue(sigma_obs_vec, "sigma_obs_vec",
                stan::model::index_min_max(1, n), stan::model::index_uni(s)),
              base_rng__), "assigning variable ypred",
            stan::model::index_min_max(1, n), stan::model::index_uni(s));
        }
      }
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "sigma_obs_adj",
        sigma_obs_adj, 0);
      out__.write(sigma_obs_adj);
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          out__.write(ypred[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(sigma_obs_vec);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<local_scalar_t__>> ar =
        std::vector<std::vector<local_scalar_t__>>(P,
          std::vector<local_scalar_t__>(n_lv, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        current_statement__ = 1;
        for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
          current_statement__ = 1;
          ar[(sym2__ - 1)][(sym1__ - 1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write_free_lub(-1, 1, ar);
      Eigen::Matrix<local_scalar_t__,-1,-1> LV_z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, n_lv, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(LV_z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(n, n_lv),
        "assigning variable LV_z");
      out__.write(LV_z);
      Eigen::Matrix<local_scalar_t__,-1,1> L =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(L,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(M),
        "assigning variable L");
      out__.write(L);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_series),
        "assigning variable alpha");
      out__.write(alpha);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_obs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(sigma_obs,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_series),
        "assigning variable sigma_obs");
      out__.write_free_lb(0, sigma_obs);
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 6;
      nu = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, nu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "ar", "double",
        std::vector<size_t>{static_cast<size_t>(P),
          static_cast<size_t>(n_lv)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "LV_z", "double",
        std::vector<size_t>{static_cast<size_t>(n),
          static_cast<size_t>(n_lv)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "L", "double",
        std::vector<size_t>{static_cast<size_t>(M)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(n_series)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_obs",
        "double", std::vector<size_t>{static_cast<size_t>(n_series)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "nu", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<local_scalar_t__>> ar =
        std::vector<std::vector<local_scalar_t__>>(P,
          std::vector<local_scalar_t__>(n_lv, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> ar_flat__;
        current_statement__ = 1;
        ar_flat__ = context__.vals_r("ar");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(ar, ar_flat__[(pos__ - 1)],
              "assigning variable ar", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(-1, 1, ar);
      Eigen::Matrix<local_scalar_t__,-1,-1> LV_z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, n_lv, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> LV_z_flat__;
        current_statement__ = 2;
        LV_z_flat__ = context__.vals_r("LV_z");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(LV_z, LV_z_flat__[(pos__ - 1)],
              "assigning variable LV_z", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(LV_z);
      Eigen::Matrix<local_scalar_t__,-1,1> L =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_flat__;
        current_statement__ = 3;
        L_flat__ = context__.vals_r("L");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(L, L_flat__[(pos__ - 1)],
            "assigning variable L", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(L);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 4;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(alpha);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_obs =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_series, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_obs_flat__;
        current_statement__ = 5;
        sigma_obs_flat__ = context__.vals_r("sigma_obs");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(sigma_obs, sigma_obs_flat__[(pos__ - 1)],
            "assigning variable sigma_obs", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma_obs);
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 6;
      nu = context__.vals_r("nu")[(1 - 1)];
      out__.write_free_lb(0, nu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"ar", "LV_z", "L", "alpha",
                "sigma_obs", "nu"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"trend", "Lambda", "LV"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"sigma_obs_adj", "ypred", "sigma_obs_vec"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(P),
                                                 static_cast<size_t>(n_lv)},
                std::vector<size_t>{static_cast<size_t>(n),
                  static_cast<size_t>(n_lv)},
                std::vector<size_t>{static_cast<size_t>(M)},
                std::vector<size_t>{static_cast<size_t>(n_series)},
                std::vector<size_t>{static_cast<size_t>(n_series)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(n_series)},
             std::vector<size_t>{static_cast<size_t>(n_series),
               static_cast<size_t>(n_lv)},
             std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(n_lv)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_series)},
             std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(n_series)},
             std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(n_series)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
        param_names__.emplace_back(std::string() + "ar" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
        param_names__.emplace_back(std::string() + "LV_z" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "L" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_obs" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "nu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "trend" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_series; ++sym2__) {
          param_names__.emplace_back(std::string() + "Lambda" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "LV" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_obs_adj" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "ypred" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "sigma_obs_vec" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
        param_names__.emplace_back(std::string() + "ar" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
        param_names__.emplace_back(std::string() + "LV_z" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      param_names__.emplace_back(std::string() + "L" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_obs" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "nu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "trend" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_series; ++sym2__) {
          param_names__.emplace_back(std::string() + "Lambda" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_lv; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "LV" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_obs_adj" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "ypred" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_series; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "sigma_obs_vec" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"ar\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(P) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(n_lv) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"LV_z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"parameters\"},{\"name\":\"sigma_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"trend\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_series) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Lambda\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_series) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"transformed_parameters\"},{\"name\":\"LV\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_obs_adj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"generated_quantities\"},{\"name\":\"ypred\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(n_series) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"sigma_obs_vec\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_series) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"ar\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(P) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(n_lv) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"LV_z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"parameters\"},{\"name\":\"sigma_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"trend\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_series) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Lambda\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n_series) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"transformed_parameters\"},{\"name\":\"LV\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_lv) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_obs_adj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_series) + "},\"block\":\"generated_quantities\"},{\"name\":\"ypred\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(n_series) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"sigma_obs_vec\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(n) + ",\"cols\":" + std::to_string(n_series) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((P * n_lv) + (n * n_lv)) + M) +
      n_series) + n_series) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((n *
      n_series) + (n_series * n_lv)) + (n * n_lv)));
    const size_t num_gen_quantities = emit_generated_quantities * (((n_series
      + (n * n_series)) + (n * n_series)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((P * n_lv) + (n * n_lv)) + M) +
      n_series) + n_series) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((n *
      n_series) + (n_series * n_lv)) + (n * n_lv)));
    const size_t num_gen_quantities = emit_generated_quantities * (((n_series
      + (n * n_series)) + (n * n_series)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_ardf_namespace::model_ardf;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_ardf_namespace::profiles__;
}
#endif
#endif
